### ISSUE TITLE
It doesn't load into minecraft

### ISSUE THREAD

**Issue by Whop42** [Enaium/FoxBase#3]
When I run it, the code never runs, it just runs minecraft 1.16.5 with mods

I have edited the client
[Source](https://github.com/DentClient/Client)

**Comment by Whop42** [comment]
I looked for help on the fabricMC discord, but they won't help because it's a hacked client

**Comment by AstroOrbis** [comment]
i had the same issue i just ended up using Meteor's code, just find a good open source client, fork theirs and make your changes

**Comment by Whop42** [comment]
I have already decided to use FoxBase, I think the problem is something with mixins

**Comment by Whop42** [comment]
It worked before

**Comment by AstroOrbis** [comment]
when i run ./gradlew build and ./gradlew runClient it fails too

**Comment by Enaium** [comment]
startup log

**Comment by AstroOrbis** [comment]
@Whop42 reclone the repo and run ./gradlew runClient, send your startup logs I'm working on another thing rn i cant

**Comment by Whop42** [comment]
I can do that tonight, I'll get back to you then. My builds are working though.

**Comment by Whop42** [comment]
I know this isn't what you asked for but now the `./gradlew build`s are failing

> Welcome to Gradle 6.7!
> 
> Here are the highlights of this release:
>  - File system watching is ready for production use
>  - Declare the version of Java your build requires
>  - Java 15 support
> 
> For more details see https://docs.gradle.org/6.7/release-notes.html
> 
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> > Configure project :
> Fabric Loom: 0.5.43 Build(release #43)
> :setting up loom dependencies
> :merging jars
> :setting up mappings (yarn 1.16.5+build.1)
> :extracting yarn-1.16.5+build.1-v2.jar
> Reading /home/runner/.gradle/caches/fabric-loom/mappings/steps/inverted-intermediary.tiny
> Reading /home/runner/.gradle/caches/fabric-loom/mappings/steps/unmerged-yarn.tiny
> Merging /home/runner/.gradle/caches/fabric-loom/mappings/steps/inverted-intermediary.tiny with /home/runner/.gradle/caches/fabric-loom/mappings/steps/unmerged-yarn.tiny
> Merged mappings written to /home/runner/.gradle/caches/fabric-loom/mappings/steps/unordered-merged.tiny
> :remapping minecraft (TinyRemapper, official -> named)
> :remapping minecraft (TinyRemapper, official -> intermediary)
> :remapping 43 mods (TinyRemapper, intermediary -> named)
> :remapping sources
> :loading intermediary -> named source mappings
> 
> > Task :compileJava
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> > Task :compileJava FAILED
> Execution failed for task ':compileJava'.
> > Could not resolve all files for configuration ':compileClasspath'.
>    > Could not resolve net.minecraft:minecraft:1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.1-v2.
>      Required by:
>          project :
>       > Could not resolve net.minecraft:minecraft:1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.1-v2.
>          > Could not get resource 'https://jcenter.bintray.com/net/minecraft/minecraft/1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.1-v2/minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.1-v2.pom'.
>             > Could not GET 'https://jcenter.bintray.com/net/minecraft/minecraft/1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.1-v2/minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.1-v2.pom'.
> 
>                > Read timed out
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4m 13s
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
> 1 actionable task: 1 executed
> Error: Process completed with exit code 1.

**Comment by AstroOrbis** [comment]
same

**Comment by Whop42** [comment]
the bintray links return 404s

**Comment by Whop42** [comment]
I fixed the `./gradlew build` with the build.gradle from the fabric example mod

**Comment by AstroOrbis** [comment]
make a pr

**Comment by Whop42** [comment]
i did, this is still not tested on actual minecraft

**Comment by AstroOrbis** [comment]
ill build and test

**Comment by AstroOrbis** [comment]
which pr theres 2

**Comment by Whop42** [comment]
the 1.16.5 one

**Comment by AstroOrbis** [comment]
ok

**Comment by Whop42** [comment]
you get it to run?

**Comment by AstroOrbis** [comment]
ima do it

**Comment by AstroOrbis** [comment]
it builds!

**Comment by AstroOrbis** [comment]
time to test it...

**Comment by AstroOrbis** [comment]
it crashes instantly :(

**Comment by AstroOrbis** [comment]
with error code 0

**Comment by Whop42** [comment]
hmm

log?

**Comment by Whop42** [comment]
@AstroOrbis what does the log say?

**Comment by AstroOrbis** [comment]
ok ill send

**Comment by AstroOrbis** [comment]
[19:58:24] [main/INFO]: Loading for game Minecraft 1.16.5
[19:58:24] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: foxbase requires {cf4m @ [>=1.4.6]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177) ~[fabric-loader-0.11.1.jar:?]
	... 5 more

**Comment by AstroOrbis** [comment]
whats cf4m, cant we install that into the mod itself like Meteor did with sodium, etc

**Comment by AstroOrbis** [comment]
https://github.com/cf4m/cf4m this is cf4m

**Comment by Whop42** [comment]
ok my fork should be fixed now, make sure to use 1.16.5

**Comment by AstroOrbis** [comment]
ok

**Comment by AstroOrbis** [comment]
im doing ./gradlew RunClient because it builds and opens a client with it at once

**Comment by AstroOrbis** [comment]
A problem occurred configuring root project 'FoxBase'.
> Could not resolve all dependencies for configuration ':modImplementation'.
   > Could not find cn.enaium.cf4m:cf4m-fabric:1.4.6.
     Searched in the following locations:
       - https://libraries.minecraft.net/cn/enaium/cf4m/cf4m-fabric/1.4.6/cf4m-fabric-1.4.6.pom
       - file:/Users/***/Desktop/FoxBase/build/loom-cache/cf4m-fabric-1.4.6.jar
       - file:/Users/***/Desktop/FoxBase/build/loom-cache/cf4m-fabric.jar
       - file:/Users/***/Desktop/FoxBase/.gradle/loom-cache/remapped_mods/cf4m-fabric-1.4.6.jar
       - file:/Users/***/Desktop/FoxBase/.gradle/loom-cache/remapped_mods/cf4m-fabric.jar
       - https://maven.fabricmc.net/cn/enaium/cf4m/cf4m-fabric/1.4.6/cf4m-fabric-1.4.6.pom
       - https://repo.maven.apache.org/maven2/cn/enaium/cf4m/cf4m-fabric/1.4.6/cf4m-fabric-1.4.6.pom
       - https://jcenter.bintray.com/cn/enaium/cf4m/cf4m-fabric/1.4.6/cf4m-fabric-1.4.6.pom
       - file:/Users/***/.gradle/caches/fabric-loom/1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.1-v2/cf4m-fabric-1.4.6.jar
       - file:/Users/***/.gradle/caches/fabric-loom/1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.1-v2/cf4m-fabric.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

**Comment by AstroOrbis** [comment]
i replaced my user with *** for privacy reasons

**Comment by AstroOrbis** [comment]
also make releases later

**Comment by Whop42** [comment]
yea i'll implement auto yarn builds sometime soon

**Comment by Whop42** [comment]
oh wow C4FM is amazing

I'll get it in today

**Comment by AstroOrbis** [comment]
whats your discord

**Comment by Enaium** [comment]
use [this mod](https://github.com/cf4m/cf4m-fabric/releases)

**Comment by AstroOrbis** [comment]
it works thx
