### ISSUE TITLE
how do i change the maven group / java class name without breaking quite literally everything

### ISSUE THREAD

**Issue by AstroOrbis** [Enaium/FoxBase#6]

**Comment by AstroOrbis** [comment]
Also the ModID, because last time i tried to do that I failed horribly and ended up breaking everything

**Comment by AstroOrbis** [comment]
other thing: the MacOS bar says this, how do i change this too :p
<img width="376" alt="Screen Shot 2021-02-23 at 9 31 49 PM" src="https://user-images.githubusercontent.com/65419194/108938687-8e188480-761e-11eb-98d3-8483eb0ab920.png">

**Comment by Enaium** [comment]
fabric wiki [fabric.mod.json](https://fabricmc.net/wiki/documentation:fabric_mod_json)

**Comment by AstroOrbis** [comment]
thanks
